name: Check Branch Protection
on: push
jobs:
  check-protection:
    runs-on: ubuntu-latest
    steps: 
      - name: Llamar API GitHub
        run:  |
          curl -H  "Authorization: token ${{ secrets.ACCESS }}" \
          https://api.github.com/repos/eulalionava/demo-zustand/branches/main/protection
